### ISSUE TITLE
Error when running all snapshots

### ISSUE THREAD

**Issue by tomitrescak** [meinaart/cypress-plugin-snapshots#10]
Hi, thanks for the amazing plugin!!!

There is a possible bug, as when I run all tests in the cypress browser I receive following error:

```
CypressError: cy.task('cypress-plugin-snapshot:matchText') failed with the following error:

> Error: Cannot load snapshot file. File "__snapshots__/__all.snap does not contain valid JSON or javascript
```

**Comment by meinaart** [comment]
This was quite hard to fix but I managed it. Probably need to contact Cypress about why `Cypress.spec` is not correct when running all tests. Or why they don't populate the "file" field in Mocha.

**Comment by meinaart** [comment]
@tomitrescak can you verify it works?

**Comment by meinaart** [comment]
I will remove the fix, it was causing other issues and the real reason is a bug in Cypress:
https://github.com/cypress-io/cypress/issues/3090

**Comment by sgnl** [comment]
IMO this issue should be mentioned on the README as it's a huge blocker for me, I only found out after implementing and writing tests (using `.only` while writing tests) to find the error in the GUI test runner after I ran all my tests which made all my work previously pretty useless.

Please consider adding an eye-catching warning or 'caveat' section which mentions this issue!

Hope Cypress gets the fix in soon, :fingers

**Comment by bahmutov** [comment]
So the workaround I can offer for now is to fix `Cypress.spec` object by looking at the `__filename` in each spec file. Here is the code to place into `cypress/support/index.js`. It is a utility function that forms `Cypress.spec` from passed filename

```js
// cypress/support/index.js
export const fixCypressSpec = filename => () => {
  const path = require('path')
  const relative = filename.substr(1) // removes leading "/"
  const projectRoot = Cypress.config('projectRoot')
  const absolute = path.join(projectRoot, relative)
  Cypress.spec = {
    absolute,
    name: path.basename(filename),
    relative
  }
}
```

From each spec file (that wants to use snapshots)

```js
import { fixCypressSpec } from '../support'

beforeEach(fixCypressSpec(__filename))
```

I have been playing with this in https://github.com/bahmutov/objection-example using this approach to run all specs with snapshots

**Comment by CSchulz** [comment]
Seems not to be working if you are using TypeScript.

**Comment by meinaart** [comment]
Investigate if this would work as a possible fix.
```
Cypress.mocha.getRunner().suite.ctx.currentTest.title
```

**Comment by diggabyte** [comment]
> Seems not to be working if you are using TypeScript.
+1 @CSchulz 

When using typescript, the workaround mentioned by @bahmutov does not work, as the `__filename` resolves to `index.js`, which is a result of the fact that typescript is being transpiled to js, so (depending on your setup), it will reference the file in which the ts -> js transformation took place (plugins/index.js, for example)

**Comment by yuriMalakhov** [comment]
> Investigate if this would work as a possible fix.
> 
> ```
> Cypress.mocha.getRunner().suite.ctx.currentTest.title
> ```

``````

**Comment by yuriMalakhov** [comment]
Typescript users, just pass the exact spec file path to `beforeEach(fixCypressSpec('/cypress/integration/spec.ts'))`.  👍

FYI @CSchulz @meinaart

**Comment by webdevisme** [comment]
Any light at the end of this tunnel? The suggested _fixes_ don't seem to work for me :(

**Comment by dploeger** [comment]
Especially for Typescript users, it's easier to use a custom command for the workaround like this:

``` javascript
Cypress.Commands.add('fixCypressSpec', (filename) => {
    const path = require('path')
    const relative = filename.substr(1) // removes leading "/"
    const projectRoot = Cypress.config('projectRoot')
    const absolute = path.join(projectRoot, relative)
    Cypress.spec = {
        absolute,
        name: path.basename(filename),
        relative
    }
})
```

add it to the index.d.ts like this:

``` javascript
/// <reference types="cypress" />

declare namespace Cypress {
  interface Chainable {
    fixCypressSpec(filename: string): void
  }
}
```

and then in the spec in a `beforeEach`:

``` javascript
describe('my test', () => {
  beforeEach(() => {
    cy.fixCypressSpec('/cypress/integration/mytest_spec.ts')
(...)
```

**Comment by skivol** [comment]
\+ if using `cypress-cucumber-preprocessor`, then one could write a "Given" step like so:
```
Given('I use snapshots for {string} feature', (fileName) => {
	cy.fixCypressSpec(fileName);
});
```
And in specs/features that use the snapshotting specify that:
`Given I use snapshots for "/cypress/integration/mytest.feature" feature`

But still would be nice to avoid all these workarounds ;)

**Comment by bmcgary** [comment]
I put the fix suggested by @bahmutov and it seems to work. But it looks like an error is thrown from getSpec.js, 
`if (Cypress.spec.absolute === '__all') {
    throw new Error('cypress-plugin-snapshots does not work when running all tests, this will be fixed once this bug is resolved: https://github.com/cypress-io/cypress/issues/3090');
  }`

If I comment this out the test works fine. The question is how do you handle this for others on the team? Tell them to npm install then go into node_modules and comment out the offending line? Is anyone else doing something more streamlined?

**Comment by Winggo** [comment]
> I put the fix suggested by @bahmutov and it seems to work. But it looks like an error is thrown from getSpec.js,
> `if (Cypress.spec.absolute === '__all') { throw new Error('cypress-plugin-snapshots does not work when running all tests, this will be fixed once this bug is resolved: https://github.com/cypress-io/cypress/issues/3090'); }`
> 
> If I comment this out the test works fine. The question is how do you handle this for others on the team? Tell them to npm install then go into node_modules and comment out the offending line? Is anyone else doing something more streamlined?

I had this problem too. Solved the issue by forking the plugin, modifying the fork by commenting out those lines that throw the error, and using that forked module in package.json.

**Comment by derting** [comment]
> I put the fix suggested by @bahmutov and it seems to work. But it looks like an error is thrown from getSpec.js,
> `if (Cypress.spec.absolute === '__all') { throw new Error('cypress-plugin-snapshots does not work when running all tests, this will be fixed once this bug is resolved: https://github.com/cypress-io/cypress/issues/3090'); }`
> 
> If I comment this out the test works fine. The question is how do you handle this for others on the team? Tell them to npm install then go into node_modules and comment out the offending line? Is anyone else doing something more streamlined?

Comment this will change the "_image_snapshots_" folder path. I suggest modify the getSpec.js below:

`
async function getSpec() {
  // if (Cypress.spec.absolute === '__all') {
  //   throw new Error(...);
  // }

  const path = require('path')
  const projectRoot = Cypress.config('projectRoot')
  const absolute = path.join(projectRoot, __filename)
  Cypress.spec = {
    absolute,
    name: path.basename(__filename),
    __filename
  }

  // console.log(Cypress.spec)
  return Promise.resolve(Cypress.spec);
}

module.exports = getSpec;
`

**Comment by krisraven** [comment]
When I apply @bahmutov's [workaround](https://github.com/meinaart/cypress-plugin-snapshots/issues/10#issuecomment-514459554 ) - it works well, thanks for this 😄  however, after running the all the test specs, a folder called  "ypress" gets created (ie.
`ypress/integration/__snapshots__/myTestSpecName.spec.js.snap`). I was wondering if this is correct or is a side effect of the workaround, as it has not been mentioned here.

**Comment by 441N143G** [comment]
There is no reason to manually specify the path: `cy.fixCypressSpec(__filename);`

**Comment by nielsboecker-zuhlke** [comment]
Thanks @dploeger and @441N143G, that's really helpful.

Btw, TypeScript users will also want to install `@types/node` and add it to their `tsconfig` in order for `__filename` to work:

```
{
    ...,
    "types": ["cypress", ..., "@types/node"],
}
```

**Comment by franck-mahieu** [comment]
> When I apply @bahmutov's [workaround](https://github.com/meinaart/cypress-plugin-snapshots/issues/10#issuecomment-514459554) - it works well, thanks for this 😄 however, after running the all the test specs, a folder called "ypress" gets created (ie.
> `ypress/integration/__snapshots__/myTestSpecName.spec.js.snap`). I was wondering if this is correct or is a side effect of the workaround, as it has not been mentioned here.

I experience the same thing, to not have "ypress" folder, you juste have to remove `substr(1)` ;)

**Comment by rdadoune** [comment]
This solution works for me universally with TypeScript:

`support/snapshotPatch.ts`:
```typescript
import { basename } from 'path';

declare global {
  // eslint-disable-next-line @typescript-eslint/no-namespace
  namespace Cypress {
    // eslint-disable-next-line @typescript-eslint/no-unused-vars
    interface Chainable<Subject> {
      /**
       * Patch cypress-plugin-snapshots
       *
       * @returns {void}
       */
      fixCypressSpec(): void;
    }
  }
}

Cypress.Commands.add('fixCypressSpec', function () {
  const { absoluteFile, relativeFile } = this.test.invocationDetails;
  Cypress.spec = {
    ...Cypress.spec,
    absolute: absoluteFile,
    name: basename(absoluteFile),
    relative: relativeFile,
  };
});

```
`support/index.ts`:
```typescript
import './support/snapshotPatch.ts';

beforeEach(() => {
  cy.fixCypressSpec();
});
```

**Comment by SShneider** [comment]
> This solution works for me universally with TypeScript:
> 
> `support/snapshotPatch.ts`:
> 
> ```ts
> import { basename } from 'path';
> 
> declare global {
>   // eslint-disable-next-line @typescript-eslint/no-namespace
>   namespace Cypress {
>     // eslint-disable-next-line @typescript-eslint/no-unused-vars
>     interface Chainable<Subject> {
>       /**
>        * Patch cypress-plugin-snapshots
>        *
>        * @returns {void}
>        */
>       fixCypressSpec(): void;
>     }
>   }
> }
> 
> Cypress.Commands.add('fixCypressSpec', function () {
>   const { absoluteFile, relativeFile } = this.test.invocationDetails;
>   Cypress.spec = {
>     ...Cypress.spec,
>     absolute: absoluteFile,
>     name: basename(absoluteFile),
>     relative: relativeFile,
>   };
> });
> ```
> 
> `support/index.ts`:
> 
> ```ts
> import './support/snapshotPatch.ts';
> 
> beforeEach(() => {
>   cy.fixCypressSpec();
> });
> ```

if i use it globally it saves all the snapshots as index.ts.snap, but works if i call it as a command within tests, which i feel is preferable anyway

**Comment by rdadoune** [comment]
@SSDlm Thanks for pointing that issue out! That's a bug I discovered shortly after I posted the above solution. I meant to come back here and update but never did 😖

**Comment by edimitchel** [comment]
The maintenance of this package is freezed.. I was added to the project but I didn't have any right for merge PR or update project settings (CICD is broken)..

**Comment by knownasilya** [comment]
Could this plugin run the fix (workaround) internally?

**Comment by chrisbraddock** [comment]
> if i use it globally it saves all the snapshots as index.ts.snap, but works if i call it as a command within tests, which i feel is preferable anyway

If you change:

```JavaScript
const { absoluteFile, relativeFile } = this.test.invocationDetails;
```
to:

```JavaScript
const { absoluteFile, relativeFile } = this.currentTest.invocationDetails;
```

it works in a global beforeEach.
