### ISSUE TITLE
Test don't fail when change text or color

### ISSUE THREAD

**Issue by rwardanjan** [meinaart/cypress-plugin-snapshots#100]
I have an issue with matching screenshots when changing colors. It will won't fail when changing color or changing the text. It will only fail when elements are not in the same place. Is there a way that he detects whether color or text changed?

**Comment by franciscotrillo** [comment]
What threshold are you using? The default configuration didn't work for me when changing text color.
I set it up this way and it works:
```
// cypress.json
"env": {
    "cypress-plugin-snapshots": {
      "imageConfig": {
        "threshold": 0.01,
        "thresholdType": "pixel"
      }
    }
  }
```

**Comment by rwardanjan** [comment]
Thanks that worked! Is there a way to show more detail in the difference? 
Is this situation he is not showing the difference very good

**Comment by guillaumebouhier** [comment]
I had the same issue while changing the text of an Angular Material button. Test was passing with results displaying "Snapshots match" even though the text of the button was changed from "open" to "close".

When adding the configuration provided by @franciscotrillo to cypress.json it worked.
It seems that default configuration is not applied for some reason.
