### ISSUE TITLE
[updateSnaphots = true] dosn't work with multiple snapshottests in one test(bug) 

### ISSUE THREAD

**Issue by AnnaLohse** [meinaart/cypress-plugin-snapshots#111]
**Describe the bug**
If updateSnapshots=true is set in the config, only the first snapshot will be corrected during execution because the test failed during the snapshot comparison and the runner stops after the test.
So if I have multiple snapshot tests in one test I have to run it several times with [updateSnapshots = true] until all snapshots are failed once and updated afterwards.

**To Reproduce**
1. set updateSnapshots in config to true
2. write test like
```
describe('MultipleSnapshottests', () => {
    it('test', () => {
        cy.get('[data-e2e="component"]')
            .toMatchSnapshot();
        cy.get('[data-e2e="component2"]')
            .toMatchSnapshot();
    });
});
```
3. run test

**Expected behavior**
When updateSnapshots ist set to true, the runner shouldn't stop after toMatchSnapshot() failed. 

**Desktop**
 - OS: Linux
 - Cypress Version "4.4.1"

**Comment by meinaart** [comment]
I am working on a fix, you are right. This is not how it should work.

**Comment by AnnaLohse** [comment]
Thanks for the quick fix, everything works perfect now.
