### ISSUE TITLE
(bug) `Config cannot be found.` when importing cypress-plugin-snapshots/command

### ISSUE THREAD

**Issue by CyrilKrylatov** [meinaart/cypress-plugin-snapshots#112]
**Describe the bug**
Hello everyone,

The `import 'cypress-plugin-snapshots/commands'` part in support/index.js as [described here](https://github.com/meinaart/cypress-plugin-snapshots#command) seems to not work as it's not importing the commands.

**To Reproduce**
0. Go to my `cypress/` folder
1. `yarn add -D cypress-plugin-snapshots`
2. open `./support/index.js`, put `import 'cypress-plugin-snapshots/commands'` in there
3. launch cypress with the gui part
4. see the following error: 
>Config cannot be found.
>
>This error originated from your test code, not from Cypress.
>
>When Cypress detects uncaught errors originating from your test code it will automatically fail the current test.

**Expected behavior**
To not have this error

**Screenshots**
![ss_ 1497](https://user-images.githubusercontent.com/1059657/81301764-c2b05500-9079-11ea-8e94-1302ae6c50b8.jpg)
![ss_ 1499](https://user-images.githubusercontent.com/1059657/81301950-04d99680-907a-11ea-95df-e790baeaf83d.jpg)

**Desktop (please complete the following information):**
 - OS: macOS Mojave 10.14.6 (18G95)
 - Cypress Version 4.5.0 / cypress-plugin-snapshots Version 1.3.0

**Additional context**
Thank you for your answers and thank you for this plugin!

**Comment by meinaart** [comment]
Is fixed in latest version.

**Comment by CyrilKrylatov** [comment]
Thank you for your quick reply!

I updated cypress-plugin-snapshots to its last version (1.4.3) and now I have the following error with the same configuration as above:

```Command:  task
cypress_runner.js:171559 Error:    CypressError: `cy.task('cypress-plugin-snapshot:getFile')` failed with the following error:

The 'task' event has not been registered in the plugins file. You must register it before using cy.task()

Fix this in your plugins file here:
false

https://on.cypress.io/api/task

Because this error occurred during a `before all` hook we are skipping all of the remaining tests.```

Did I miss something?

Thank you!
