### ISSUE TITLE
Base64 library is missing

### ISSUE THREAD

**Issue by redaxmedia** [meinaart/cypress-plugin-snapshots#126]
There are multiple factors coming together here. It seems that `js-base64` is missing their minified versions since a couple of releases and that you are using this instead of the original file that btw. is way better for tree shaking.

## Code

```
module.exports = {
  PATH_BASE64_JS: 'js-base64/base64.min.js',
  PATH_CSS: './assets/styles.css',
  PATH_DIFF_CSS: 'diff2html/dist/diff2html.css',
  PATH_DIFF_JS: 'diff2html/dist/diff2html.js',
  PATH_JS: './assets/script.js',
  PATH_SOCKET_JS: 'socket.io-client/dist/socket.io.js',
};
```

## Fix

A proper fix would be to get rid of this anti-pattern and use `require('js-base64')` instead. Same for the other libraries... you are doing it wrong :-)

```
module.exports = {
  PATH_BASE64_JS: 'js-base64/base64.js',
  ...
};
```

## Error

Monday builds are broken as of that error... friday builds that have been okay before the weekend are broken on re-run aswell:

```
"before all" hook for "Setup":
CypressError: `cy.task('cypress-plugin-snapshot:getFile')` failed with the following error:

> Cannot find module 'js-base64/base64.min.js'
Require stack:
- /home/.../node_modules/cypress-plugin-snapshots/src/tasks/getFile.js
- /home/.../node_modules/cypress-plugin-snapshots/src/tasks/index.js
- /home/.../node_modules/cypress-plugin-snapshots/plugin.js
```

## Environment

- OS: Ubuntu 20.04
- Cypress Version 4.6.0 / 4.8.0
- NodeJS: 12.16.1

**Comment by canakg** [comment]
+1
Any known workarounds we can apply?

**Comment by redaxmedia** [comment]
@canakg 

You are free to use my fork or just create your own for the moment by editing `paths.js` like I did here https://github.com/redaxmedia/cypress-plugin-snapshots/commit/878ba154e8ae8ad2bc33ec17c8456b3192988a77:

```
"dependencies":
{
    "cypress-plugin-snapshots": "git+https://github.com/redaxmedia/cypress-plugin-snapshots.git"
}
```

**Comment by redaxmedia** [comment]
Set `"js-base64": "2.5.2" ` in your local `package.json` like mentioned in the pull request https://github.com/meinaart/cypress-plugin-snapshots/pull/125

**Comment by brndto** [comment]
Seems like it's trying to find
`js-base64` instead of `base64-js`

What fixed it:
`>npm install js-base64@2.5.1 -S`

**Comment by daviddekanter** [comment]
@brndto i tried your suggestion, the error is gone, but no image snapshots taken. anyone else has the same problem?
