### ISSUE TITLE
(bug) Cannot find module 'js-base64/base64.min.js'

### ISSUE THREAD

**Issue by kirill-konshin** [meinaart/cypress-plugin-snapshots#136]
**Describe the bug**

Install, run, observe the issue:

```
cy.task('cypress-plugin-snapshot:getFile') failed with the following error:
> Cannot find module 'js-base64/base64.min.js'
```

![image](https://user-images.githubusercontent.com/1530410/87488117-60814c80-c5f4-11ea-97f4-9398bcdbe869.png)

The reason is that file referenced in 
https://github.com/meinaart/cypress-plugin-snapshots/blob/31fd4a5b38409b98c47e76142d862b257ac7dd7f/src/paths.js#L2

Actually is not present in the package:
![image](https://user-images.githubusercontent.com/1530410/87488058-329c0800-c5f4-11ea-83ae-281c8beb9c9f.png)

It was there in version [2.5.x](https://unpkg.com/browse/js-base64@2.5.0) and in [2.6.x](https://unpkg.com/browse/js-base64@2.6.0) it is removed. The version installed with `cypress-plugin-snapshots` is currently `2.6.3`.

I suggest to narrow the version range.

**Comment by kirill-konshin** [comment]
Just noticed #125 and #134. Please prioritize the merge as currently plugin is not usable unless you do something like this in `package.json`:

```json
{
  "resolutions": {
    "js-base64": "2.5.2"
  }
}
```

**Comment by wes-r** [comment]
NOTE: Ran into the same issue. Above work around resolved it.

**Comment by skivol** [comment]
Same here, had to use https://www.npmjs.com/package/npm-force-resolutions when using npm and not yarn.

**Comment by alexlee-dev** [comment]
Yep. Looks like

## NPM Solution
1. Add 
```
{
  "resolutions": {
    "js-base64": "2.5.2"
  }
}
```
2. Add
```
"scripts": {
  "preinstall": "npx npm-force-resolutions"
}
```

## Yarn Solution
1. Add 
```
{
  "resolutions": {
    "js-base64": "2.5.2"
  }
}
```

**Comment by zakkor** [comment]
Unfortunately it looks like the project is dead

**Comment by ChanManChan** [comment]
install this  "@types/js-base64": "^2.0.0" <- this works for me 
![Annotation 2020-08-08 203131](https://user-images.githubusercontent.com/42992965/89713582-4437bc00-d9b6-11ea-80c6-1ac751b022fd.jpg)

**Comment by meinaart** [comment]
> Unfortunately it looks like the project is dead

Not really, just not working on it constantly. This should be fixed in the latest release.
