### ISSUE TITLE
Version 1.2.3 breaks non-browserify cypress setup

### ISSUE THREAD

**Issue by SBoudrias** [meinaart/cypress-plugin-snapshots#14]
The release 1.2.3 appear to be forcing the default browserify preprocessor. https://github.com/meinaart/cypress-plugin-snapshots/commit/b36fb9c1c21f619ab9b3743312c6eb20fe8ef29d#diff-7aa2d6e03c8f7e1334d6724f903c6819R26

This breaks our project using `@cypress/preprocessor-webpack` because no processing is done; so the JS syntax isn't valid and throw a parsing exception.

**Comment by meinaart** [comment]
I was afraid of that already. I think I just have to break the support for "Running all tests" again to fix your issue.

I reported a bug to address the underlying issue for "All tests":
https://github.com/cypress-io/cypress/issues/3090

**Comment by SBoudrias** [comment]
Thanks for being so responsive on issues we're raising 😄
