### ISSUE TITLE
(bug) Display snapshot error when click compare snapshot button first time

### ISSUE THREAD

**Issue by candy-Tong** [meinaart/cypress-plugin-snapshots#145]
**Describe the bug**
The test have a image snapshot error. I click the compare snapshot button. Two image it display are the diff.
![image](https://user-images.githubusercontent.com/20377280/92094185-be692e00-ee06-11ea-908f-83037dd9ff50.png)
And i close the modal, and compare again. It display right.

**To Reproduce**

**Expected behavior**
When click the  compare snapshot, it dispplay the exprected result and Actual result.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Cypress Version 5.1.0

**Additional context**

**Comment by taninnazar** [comment]
@meinaart Hello, I have the same issue. I guess it's Windows-related error. Would be nice to fix that

**Comment by Norfeldt** [comment]
@taninnazar I'm using macOS and having the same issue

```
$ yarn cypress version
yarn run v1.22.5
$ /<path to repo>/<repo>/node_modules/.bin/cypress version
Cypress package version: 5.6.0
Cypress binary version: 5.6.0
```

> package.json

```
"devDependencies": {
   ...
   "cypress-plugin-snapshots": "^1.4.4",
   ...
}
```

**Comment by vio-codes** [comment]
@taninnazar I have the same issue on macOS, basically for imageSnapshot when I click for the first time <compare snapshots> the actual and the expected image are the same. Clicking again on the button does the trick and than it works just fine.
