### ISSUE TITLE
Fix updating of snapshots when variables are used

### ISSUE THREAD

**Issue by meinaart** [meinaart/cypress-plugin-snapshots#17]

**Comment by niant** [comment]
Does this mean that snapshots are not updated when generating a bunch of tests in a forEach-loop for example? At least autoCleanUp does not seem to work for me in such cases.

```javascript
describe('suite', => {
  [1, 2, 3].forEach(number => {
    it('should be '+ number, () => {
       cy.get('x').toMatchSnapshot();
    });
  })
})
```

**Comment by meinaart** [comment]
No, I think that should work. There is a feature to use variables inside your snapshots. But when you want to patch those the variables are overwritten.
