### ISSUE TITLE
Cypress Peer Dependency

### ISSUE THREAD

**Issue by vipin705** [meinaart/cypress-plugin-snapshots#183]
will the Cypress Peer Dependency get update? i see its still on 4.5.0 which is very old.

**Comment by Izhaki** [comment]
We get:

```
▶ npm audit fix
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: @webpoker/tools@0.0.2
npm ERR! Found: cypress@5.2.0
npm ERR! node_modules/cypress
npm ERR!   dev cypress@"5.2.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer cypress@"^4.5.0" from cypress-plugin-snapshots@1.4.4
npm ERR! node_modules/cypress-plugin-snapshots
npm ERR!   dev cypress-plugin-snapshots@"^1.4.4" from the root project
```

Although the plugin clearly works with `cypress@5.2.0`. I would submit a PR to change the peer dependency to change the peer dependency to:

```
  "peerDependencies": {
    "cypress": ">=4.5.0"
  },
```

But I don't know if this plugin works with cypress versions higher than 5.2

**Comment by vipin705** [comment]
i am on "cypress": "^7.1.0" and it works fine locally on my machine.

**Comment by vipin705** [comment]
@meinaart when can we expect this to be merged and published ?

**Comment by vipin705** [comment]
has this fix been released?

**Comment by ozkoidi** [comment]
Any news on this? I just got the error with Cypress 9.5.1

![image](https://user-images.githubusercontent.com/42638799/157220344-9a50a490-a596-468e-9821-a91737f02838.png)

**Comment by david-renner-dwg** [comment]
@ozkoidi were you ever able to resolve that issue from your screenshot?

**Comment by t3hmrman** [comment]
Looks like a reasonable fork has happened => https://www.npmjs.com/package/@mosofsky/cypress-plugin-snapshots

(Make sure to review the commits since this repo yourself!)
