### ISSUE TITLE
Is this plugin still maintained ?

### ISSUE THREAD

**Issue by edimitchel** [meinaart/cypress-plugin-snapshots#194]
Hello !

I don't see any update on this Cypress plugin, and what I see, a lot of people use it.

What could we do for making this plugin alive again ?
I would be volunteer to be maintainer with someone else.
cc @elevatebart @jennifer-shehane

#193 #192 #191 #189 #187 #186 #185 #184 ...

**Comment by cassus** [comment]
It would be great!

Maybe @kpdecker is interested, he has a fork on npm

**Comment by jennifer-shehane** [comment]
@edimitchel This plugin is not maintained by the Cypress team, so would need cooperation with the maintainer of the plugin or a fork of the current code base.

**Comment by meinaart** [comment]
I welcome additional maintainers.

**Comment by meinaart** [comment]
I added you as a collaborator @edimitchel You are welcome to resolve open issues.

**Comment by MikeMcC399** [comment]
@meinaart / @edimitchel 

There hasn't been a release since [v1.4.4](https://github.com/meinaart/cypress-plugin-snapshots/releases/tag/v1.4.4) on Aug 11, 2020, which is almost one year ago.

Are you able to make a new release covering the issues which have been fixed since the last release?

**Comment by lastlink** [comment]
@meinaart  you need to add @MikeMcC399  to the npm package so he can add a release to it.

**Comment by MikeMcC399** [comment]
@lastlink 
> @meinaart you need to add @MikeMcC399 to the npm package so he can add a release to it.

I don't quite understand what you meant here. I wasn't planning to play an active role in creating a new release.

**Comment by dhulme** [comment]
I'm happy to help as well @edimitchel, do you have permission to merge the open PRs now?

**Comment by edimitchel** [comment]
I'm not always available, so for sure, you help is welcome.
I do, I guess, have permission to merge open PR but there are problem on github action which blocks them..
