### ISSUE TITLE
Is it possible to remove the separator when generating the file name?

### ISSUE THREAD

**Issue by OldBody** [meinaart/cypress-plugin-snapshots#198]
Hi.
In my case, the test goes in two stages - the first collection of actual snapshots of pages. The second is to compare them with pages from the test environment.
The problem is that cypress.json has a parameter to rerun the test if 
```
"retries" fails: {
    "runMode": 2}

```
In my case, during the first stage of testing, the files are named `filename # 0.png`, but problems are observed in the second stage. If there are differences, then cypress restarts the test and the file name becomes `filename # 1.png` and for the plugin it becomes the reference thus the test is considered successful, although it is not.

**Comment by edimitchel** [comment]
Should be fixed by #169
