### ISSUE TITLE
Safe access to config properties

### ISSUE THREAD

**Issue by bahmutov** [meinaart/cypress-plugin-snapshots#2]
Hi, 

First: ❤️ and 👏 
Second: ❤️ and 👏 
Third: when checking config options like 

```
function cleanUpSnapshots() {
  const config = getConfig();
  if (!config.autoCleanUp) {
    return;
  }
  ...
```
you cannot assume `config` is not null (or maybe have logic in `getConfig()` to merge user config with defaults).

right now for this `cypress.json` file I get a crash

```json
{
  "baseUrl": "http://localhost:3000",
  "ignoreTestFiles": [
    "**/*.snap",
    "**/__snapshot__/*"
  ]
}
```

<img width="456" alt="screen shot 2018-11-09 at 12 06 41 pm" src="https://user-images.githubusercontent.com/2212006/48277281-37b8b500-e418-11e8-87fe-1bd4da3f7250.png">

:)

**Comment by bahmutov** [comment]
to work around this had to put empty object

```json
{
  "baseUrl": "http://localhost:3000",
  "ignoreTestFiles": [
    "**/*.snap",
    "**/__snapshot__/*"
  ],
  "env": {
    "cypress-plugin-snapshots": {}
  }
}
```

**Comment by meinaart** [comment]
Thanks for your feedback. That's indeed a good find. I will fix the bug.

**Comment by meinaart** [comment]
@bahmutov I removed the config from my `cypress.json` in the test repo and my fix seems to work. 

Can you verify if it also works in your setup?

**Comment by bahmutov** [comment]
Will try when I have a second, thank you

**Comment by bahmutov** [comment]
almost good: you forgot to add folder "tasks" to "files" list in the package.json, thus they are missing in the installed node_modules

```
Error: Cannot find module './tasks/task-names'
at Function.Module._resolveFilename (module.js:485:15)
at Function.Module._load (module.js:437:25)
at Module.require (module.js:513:17)
at require (internal/module.js:11:18)
at Object. (/Users/gleb/git/cypress-example-recipes/examples/blogs__testing-redux-store/node_modules/cypress-plugin-snapshots/save-server.js:3:18)
```
