### ISSUE TITLE
The task matchSnapshot takes very long with large snapshots and times out

### ISSUE THREAD

**Issue by shpuld** [meinaart/cypress-plugin-snapshots#24]
When matching a large snapshot, it can take long (10-30 seconds on regular amount of data in our application, which can mean 20-50k line snapshots, if that's any indication) to perform the task. Sometimes with a bit more data it even times out with our 2 minute task timeout. When this happens, the console has a lot of GET socket.io 500 errors, which seem to time out at 30 seconds each.

To me it would seem like there's a 30 second timeout for that socket.io get and if matching the snapshot regularly goes over that, it will never finish, but that's just my speculation without looking at the code.

**Comment by shpuld** [comment]
After trying out more things, I noticed that disabling prettier and json normalization makes it really fast! This circumvents the problem somewhat, although it would still be nice to be able to have the slower ones be a bit more stable.

**Comment by meinaart** [comment]
I will consider adding configurable timeouts. I will investigate but I think you assumptions are correct. We run into both a socket.io timeout and Cypress timeout setting.

**Comment by shpuld** [comment]
Yes I believe you're right here, after increasing the task timeout even more, some of the slower tests eventually finish with prettier enabled. I think it's safe to close this issue if there's already a way to a) make tests faster by disabling prettier and b) make them finish by giving them even more time. Either way the slowness seems to be all prettier and not in your hands.
