### ISSUE TITLE
typescript support

### ISSUE THREAD

**Issue by jtushman** [meinaart/cypress-plugin-snapshots#27]
Hi friends,

I am love the promise of this plugin.  I am using typescript for my tests.

Currently when i run .toMatchSnapshot()  it puts the snapshot in the dist folder.

Is it possible for us to configure it to point to a different target i.e. `../src`

Is there a config setting somewhere that I can take advantage of?

===== second (and happy to make a separate issue) ===
be cool if we could add typings, or instructions on how to extend the cypress name space so I do not need to do 

  // @ts-ignore
  cy.getByTestid('chart-engagement').toMatchSnapshot();

Thanks!!!!

**Comment by jtushman** [comment]
Note what I did for now was to add the following to my package.json:

```
    "snapshot:distToSrc": "copyfiles -u 2 './dist/cypress/**/__snapshots__/**' ./cypress",
    "snapshot:srcToDist": "copyfiles -u 1 './cypress/**/__snapshots__/**' ./dist/cypress"
```

and

after I generate new snaps, I run snapshot:distToSrc

and in my build step I run snapshot:srcToDist

**Comment by tgecho** [comment]
How do you have typescript set up? I have a new project set up according to the [Cypress docs](https://docs.cypress.io/guides/tooling/typescript-support.html#Transpiling-TypeScript-test-files) and snapshots seem to be generated in the correct locations out of the box.

**Comment by Maxim-Mazurok** [comment]
For those who landed here searching how to fix `Property 'toMatchImageSnapshot' does not exist on type 'Chainable<Document>'`:

```
// -- Example Usage: 
// -- cypress/tsconfig.json
// {
//   "compilerOptions": {
//      "types": ["cypress", "cypress-plugin-snapshots"]
//    }
// }
```
from https://github.com/meinaart/cypress-plugin-snapshots/pull/36/files#diff-093ad82a25aee498b11febf1cdcb6546e4d223ffcb49ed69cc275ac27ce0ccce

(TL;DR add `cypress-plugin-snapshots` to `types` in `tsconfig.json`)
