### ISSUE TITLE
escape char in html element while using toMatchSnapshot

### ISSUE THREAD

**Issue by svorkapic** [meinaart/cypress-plugin-snapshots#28]
I'm using
- cypress 3.1.5
- cypress-plugin-snapshots 1.2.5

I've seen that using of `toMatchSnapshot` on html element will not match the snapshot if the snapshot file contains elements with backslash.

In my example input element had pattern with backslash:
`<span class="input input--number   input--required">
<input type="number" name="new_address.house_number" value="" pattern="\d*" required="" data-date-format="mm/dd/yyyy"/>
</span>`

Although in first iteration snapshot was created correctly and in every other test run before closing cypress runner, it passed successfully I guess due to caching of the snapshot file but after closing the runner and running the test again it failed due to mismatch while comparing with snapshot
backslash was not included in the snapshot:
` -                      pattern="d*"`
`+                      pattern="\d*"`

I fixed this by adding additional backslash to the snapshot file manually because it would seem it's escaping it while doing the compare but I guess all backslash should be ignored while doing such comparison?

**Comment by meinaart** [comment]
I can't reproduce this. What OS are you using? Are you testing in Chrome or Electron?

I develop on a Mac, it might be Windows/Linux related.

For me it works fine.

**Comment by meinaart** [comment]
Wait, I can reproduce it.

**Comment by svorkapic** [comment]
Just to fill in some blanks about this I was using it on Mac, and it was a case on both chrome and electron.

I've checked now with version 1.2.6 and I see that now snap files are automatically created with additional escaping char in it and therefor it works out of the box.

Thanks for the quick fix!

**Comment by meinaart** [comment]
You are welcome. Glad my fix worked. I added this use case to my test set so it should not break on new releases :).
