### ISSUE TITLE
Cypress 3.1.5 and list cypress-plugin-snapshots 1.2.5 update snapshots not working.

### ISSUE THREAD

**Issue by renelux** [meinaart/cypress-plugin-snapshots#29]
With the above combination snapshots are not being updated when the setting is set to true, removing the image running the spec works fine.

**Comment by meinaart** [comment]
Are you sure it's not updated on disc? There is a severe caching issue with snapshots that I need to fix. Perhaps it only seems to be not working?

Although this issue should not occur with images. Just want to get all the info needed to fix the bug.

**Comment by renelux** [comment]
I didn't have time yet to dig deeper and see where it goes wrong, but at the moment it is not working for us at all. 

I will try to do a deeper dive and see if I can find the root cause.

**Comment by renelux** [comment]
We had a local environment issue (docker was not loading the latest code) that resulted in the images not being updated.

We did stumble on a small bug which we fixed in this PR https://github.com/meinaart/cypress-plugin-snapshots/pull/31
