### ISSUE TITLE
Publish new version

### ISSUE THREAD

**Issue by renelux** [meinaart/cypress-plugin-snapshots#33]
@meinaart could you publish a new version with the fix I provided last week?

**Comment by rlux-aa** [comment]
@meinaart I see that you weren't able to publish it yet, if needed we can help you maintain this package.

**Comment by renelux** [comment]
@meinaart I see that you weren't able to publish it yet, if needed we can help you maintain this package.

**Comment by meinaart** [comment]
Release a new version today.
