### ISSUE TITLE
toMatchSnapshot() not work on Angular

### ISSUE THREAD

**Issue by hoangtranson** [meinaart/cypress-plugin-snapshots#38]
After re-run my test I failed on snapshot since some attr is changed even it is from Angular.

![Untitled](https://user-images.githubusercontent.com/35447677/58393926-72f89980-8073-11e9-87cb-0dcc38483956.png)

Is there anyway to ignore this? Or this is an issue we cant resolve right now?

**Comment by hoangtranson** [comment]
I really need a way to ignore _nghost-* or _ngcontent-* attr for angular.

**Comment by jansivans** [comment]
This can help you https://github.com/cypress-io/snapshot/issues/79#issuecomment-507689244

**Comment by hoangtranson** [comment]
> This can help you [cypress-io/snapshot#79 (comment)](https://github.com/cypress-io/snapshot/issues/79#issuecomment-507689244)

I switched to Jest and it worked very well. [Here ](https://itnext.io/how-i-do-configure-jest-to-test-my-angular-8-project-2bd84a21d725) is my article about it.

**Comment by meinaart** [comment]
Jest is awesome. I think this functionality should not be part of this plugin. You can write your own custom command to clean up your HTML as mentioned by @jansivans.
