### ISSUE TITLE
feat: customize` __image_snapshots__` folder path

### ISSUE THREAD

**Issue by HOUCe** [meinaart/cypress-plugin-snapshots#70]
Hi guys, thanks for the great work of  cypress-plugin-snapshots. I am currently working on implementing cypress-plugin-snapshots for my project, and I really want to customize` __image_snapshots__` folder path.

Actually we **use cypress during CI pipeline**: as soon as the alpha(pre-release) deployment done, we will run cypress(and cypress-plugin-snapshots of course). In order to provide the snapshots' result, we have to configure  ` __image_snapshots__` folder to a persist path in docker.

I consult the code source and supposed that making ` __image_snapshots__` folder path configurable is not hard and reasonable(at least by my side). Cypress also provide the ability to configure `screenshotsFolder` and `videosFolder`.

I am looking forward to your reply and ready to make a PR if it is needed.

Thanks again.

**Comment by Tay08** [comment]
@HOUCe can you show us your workaround please?

**Comment by HOUCe** [comment]
In `cypress-plugin-snapshots/src/utils/image/getSnapshotFilename.js` file: 
https://github.com/meinaart/cypress-plugin-snapshots/blob/cf07698779b40f1735cc1486cb3aa9fdcadd1f7d/src/utils/image/getSnapshotFilename.js#L6

By adding a custom path(use `customAssestsPath` for example)
modify: 
```
 const dir = path.join(path.dirname(testFile), DIR_IMAGE_SNAPSHOTS);
```
to:
```
const dir = customAssestsPath ? path.join(customAssestsPath, DIR_IMAGE_SNAPSHOTS);  : path.join(path.dirname(testFile), DIR_IMAGE_SNAPSHOTS);
```

**Comment by fr0** [comment]
I would like this same feature -- can this issue be re-opened?

**Comment by NagaMukka** [comment]
Hi Guys,
I am new to cypress automation and I included snapshot plugin into my project. So, did anyone found how we can **customize __image_snapshots__ folder path.**
