### ISSUE TITLE
Warning when installing via yarn

### ISSUE THREAD

**Issue by fr0** [meinaart/cypress-plugin-snapshots#73]
**Describe the bug**
```
warning cypress-plugin-snapshots > uws@100.0.1: New code is available at github.com/uNetworking/uWebSockets.js
```

**To Reproduce**
1. `yarn add --dev cypress-plugin-snapshots`

**Expected behavior**

No warning should occur when installing.

**Desktop (please complete the following information):**
 - Mac OS 10.13.6
 - node v12.12.0
 - yarn 1.19.1

**Comment by fr0** [comment]
It looks like the `uws` npm package is deprecated. https://www.npmjs.com/package/uws

**Comment by meinaart** [comment]
Yeah, but it was needed to let socket.io function properly. The author of uws deprecated it's package because of disagreements with NPM if I remember correctly. For now just ignore the warning.
