### ISSUE TITLE
Error: listen EADDRINUSE: address already in use 127.0.0.1:2121

### ISSUE THREAD

**Issue by vomc** [meinaart/cypress-plugin-snapshots#76]
**Describe the bug**
Error: listen EADDRINUSE: address already in use 127.0.0.1:2121 after installing plugin according to the README and then restarting cypress

**To Reproduce**
1. Install this plugin and follow the README exactly 
> Clean up the `cypress.json` config so that it is valid json...
2. Restart cypress
3. See `Error: listen EADDRINUSE: address already in use 127.0.0.1:2121` in the app

**Expected behavior**
I would expect that the plugin works

**Screenshots**
![Screenshot 2019-11-21 at 14 39 31](https://user-images.githubusercontent.com/78635/69342879-bfacde00-0c6c-11ea-8b5b-88219f489ccf.png)

**Desktop (please complete the following information):**
 - OS: macos Mojave 10.14.6 (18G87)
 - Cypress Version 3.6.1

**Comment by kmsauter** [comment]
The error message you're seeing is because the port 2121 is being used by something else on your computer. In your cypress.json file, set the serverPort to something other than 2121 (3000 worked for me). 

`"cypress-plugin-snapshots": {`
      `"serverPort": 3000"`
   `}`
