### ISSUE TITLE
Snapshoting mulitple elements returns empty objects

### ISSUE THREAD

**Issue by K41eb** [meinaart/cypress-plugin-snapshots#77]
**Describe the bug**

If you use `toMatchSnapshot();` after a `cy.get()` that returned multiple elements, the final snapshot will look something like this: `[{}, {}, {}]`

**To Reproduce**
1. `cy.get('div').toMatchSnapshot();` when there are mutiple `div`s in the current context.

**Expected behavior**
An array of stringified dom elements.

**Desktop (please complete the following information):**
 - OS: Windows
 - Cypress Version 3.6.1

**Comment by kmsauter** [comment]
This is the same issue as #67, there's an open pull request (#79) with a fix for this.

**Comment by K41eb** [comment]
Gud
