### ISSUE TITLE
(feat) Add the option to filter out patterns

### ISSUE THREAD

**Issue by K41eb** [meinaart/cypress-plugin-snapshots#78]
**Is your feature request related to a problem? Please describe.**
It is currently impossible to ignore anything while snapshoting a DOM element or a DOM tree. Which means that snapshot testing is simply impossible for application where `id`s are generated, e.g. in Angular ag-grid generates row ids dynamically therefore two snapshots of the grid will never be the same since all `id`s have been changed.

**Describe the solution you'd like**
An option to ignore elements attributes, or the possibility to pass a function to freely `str.replace()` anything on the stringified DOM tree. 

**Describe alternatives you've considered**
Selecting several elements that do not have generated `id`s with `cy.get()`. Doesn't work as this feature is broken/missing.

**Comment by K41eb** [comment]
I would have happily done it myself but the _lack_ (absence) of documentation killed my motivation.

**Comment by meinaart** [comment]
This might work (untested):
```
cy.get('div')
  .its('outerHtml')
 .then(html => html.replace(/ id=\".*?\"/g, ''))
  .toMatchSnapshot();
```

**Comment by meinaart** [comment]
@K41eb let me know if it works. If it does not, I will reopen this issue.
