### ISSUE TITLE
toMatchImageScreenshot stripping screenshot arguments

### ISSUE THREAD

**Issue by renelux** [meinaart/cypress-plugin-snapshots#8]
In the current implementation it seems that the usual `screenshot` options are stripped from the `toMatchImageSnapshot` command.

```javascript
cy.get(`.header-bar`).toMatchImageSnapshot({
    clip: { x: 0, y: 0, width: 300, height: 50 }
});
```

This provides the following output:

**CommandOptions**
```javascript
{
  "autoCleanUp": false,
  "autopassNewSnapshots": true,
  "diffLines": 3,
  "excludeFields": [],
  "ignoreExtraArrayItems": false,
  "ignoreExtraFields": false,
  "normalizeJson": true,
  "prettier": true,
  "imageConfig": {
    "createDiffImage": false,
    "resizeDevicePixelRatio": true,
    "threshold": 0.01,
    "thresholdType": "percent"
  },
  "prettierConfig": {
    "html": { "parser": "html", "tabWidth": 2, "endOfLine": "lf" }
  },
  "serverEnabled": false,
  "serverHost": "localhost",
  "serverPort": 2121,
  "token": "2420dd834febe1b6ea977fa70d1303366cb535e53aa48cab6a509c8bf6029950543dd8ce47c8311a39601d65144510088f56e9f34fb658b7c87e24b7b47e9892",
  "updateSnapshots": true,
  "clip": { "x": 0, "y": 0, "width": 300, "height": 50 }
}
```

**ScreenshotConfig**
```javascript
{"blackout":[".snapshot-diff"],"capture":"fullPage","log":false}
```

Is this expected behavior?

**Comment by meinaart** [comment]
It is expected. But I like your suggestion to give access to the screenshot settings. I will think about how to best integrate it.

**Comment by renelux** [comment]
yes, so for us it is definitely `blackout` and `clip` that are beneficial to have access to. But in general we should be able to safely pass along everything, right?

**Comment by meinaart** [comment]
Yeah I could make it like that. But I do need some of the options for internal use. I can work around it I guess. I will try to come up with a nice solution.

**Comment by meinaart** [comment]
Added support for screenshot configuration options. You can use `blackout` and `clip` now.

**Comment by renelux** [comment]
Thanks for moving so quick 👍
