### ISSUE TITLE
Project Status

### ISSUE THREAD

**Issue by IvanFon** [meinaart/cypress-plugin-snapshots#93]
Hello @meinaart!

Thank you for creating this library, it's very useful :)

I was wondering what the status of the project is. It seems that the last activity was in August 2019, and there are a few pending pull requests and open issues. Are you still planning on maintaining this, or should it be forked instead?

Thank you!

**Comment by meinaart** [comment]
I am short on time so additional maintainers would be welcome.

**Comment by lots0logs** [comment]
@meinaart If you need some help I'd be happy to lend a hand. This package is important to our workflow at the company I work for.

**Comment by meinaart** [comment]
Pull requests are welcome.
