### ISSUE TITLE
(feat) option du change the "#" for screenshot number in filename

### ISSUE THREAD

**Issue by lordfpx** [meinaart/cypress-plugin-snapshots#95]
**Is your feature request related to a problem? Please describe.**
I'm using generated screenshot in an HTML page as background-image of elements. Unfortunatly, the `#` character break the url leading to a 404 (the filename is cut) 

**Describe the solution you'd like**
Maybe add an option to change the `#` character?

**Additional context**
My test are run on lot of components. At the same time, we generate a component index page with screenshots. We would like to use generated image snapshots for that.

Thanks a lot

**Comment by meinaart** [comment]
Should be fixed in next release.

**Comment by meinaart** [comment]
Fixed in v1.3.0
