### ISSUE TITLE
Release 1.3.0 to npmjs

### ISSUE THREAD

**Issue by wesselvanderlinden** [meinaart/cypress-plugin-snapshots#99]
My cypress tests generate a lot of warnings because of https://github.com/meinaart/cypress-plugin-snapshots/issues/92 , which is fixed in version 1.3.0. But that version isn't available in npm's package registry. The latest version there is 1.2.9.

So when is the 1.3.0 version deployed to npm? :)

**Comment by meinaart** [comment]
I just published it.
